Fixes issue # 2782, handling of add_destination duplicates.
pywbem/pywbem pull request #2784
Opened 2021-10-21 17:29 UTC by KSchopmeyer

Wating on priority prs #2795

Moves the test for duplicated name property to before the test for
duplicated URL and adds PersistenceType as test for equality between new
and existing owned destination instances.

Fixed test_subscriptionmanager.py to account for possible multiple
destination definitions in test since the code has been changed to now
allow only a single destination for each call.

NOTE: It would not bother me if we changed the code to return ValueError if the URL matched or even just to
remove the test for URL code.  I chose returning the existing instance as one of 3 generally almost equal
choices.

Added tests specifically for duplicated destination destination_id and
for returning instance if url and persistence type match.

2021-11-09 18:21 UTC, andy-maier commented on pywbem/_subscription_manager.py
> +          URL and 'PersistenceType' already exists, it is returned without
Use backquotes around property names.

2021-11-09 18:22 UTC, andy-maier requested changes

2021-11-09 18:22 UTC, andy-maier commented on pywbem/_subscription_manager.py
> +        with the same value of the `Destination` and 'PersistenceType'
Use backquotes around property names.

2021-11-09 18:22 UTC, andy-maier commented on pywbem/_subscription_manager.py
> +        destination_id of the submitted 'Name' property.
Use backquotes around property names.

2021-11-11 01:52 UTC, KSchopmeyer commented on pywbem/_subscription_manager.py
> +          URL and 'PersistenceType' already exists, it is returned without
DONE

2021-11-11 01:52 UTC, KSchopmeyer commented on pywbem/_subscription_manager.py
> +        with the same value of the `Destination` and 'PersistenceType'
DONE

2021-11-11 01:52 UTC, KSchopmeyer commented on pywbem/_subscription_manager.py
> +        destination_id of the submitted 'Name' property.
DONE

2021-11-18 06:44 UTC, andy-maier approved these changes

2021-11-18 06:44 UTC, merged