Fix issue with losing indications send by OpenPegasus
pywbem/pywbem pull request #3084
Opened 2023-11-20 17:10 UTC by KSchopmeyer

UNDER WORK, DO NOT COMMIT

This PR was prepared for two reasons:

1. Modify the pywbem listener to insert a queue between the indication receiver and the consumer call.  NOTE: Currently this adds the queue but also leaves in the current code with a flag in the pywbem listener to allow using either until we sort out the issue with actually losing indications.
2. It will try to fix the issue with losing indications but that is still open.
3. Makes changes to the examples directories to help with tracking down the lost indications issue.

Read issue #3022 for more detailed information on the issue with finding the lost indications problem.

2024-01-07 22:52 UTC, KSchopmeyer commented
QUESTION: This code is clean now except for the flag in the indication receiver code to allow either the direct callback or callback through the python interprocess queue.  Can we leave that code in? Can we commit these changes with that code.

2024-03-27 07:18 UTC, andy-maier commented
**DISCUSSION:** Does this PR, when complete, address issue #3084 such that we can close the issue?

2024-04-02 15:45 UTC, andy-maier commented
I suggest to separate the support for a queued callback interface into a separate PR.

2024-04-14 17:18 UTC, KSchopmeyer commented
Currently failing install test for Python 3.8+

```

removing 'pywbem-1.7.dev1' (and everything under it)
Successfully built pywbem-1.7.dev1.tar.gz
Makefile: Done creating the source distribution archive: dist/pywbem-1.7.0.dev1.tar.gz
Makefile: Running install tests
tests/installtest/test_install.sh dist/pywbem-1.7.0.dev1-py2.py3-none-any.whl dist/pywbem-1.7.0.dev1.tar.gz python
Error: Source distribution archive does not exist: dist/pywbem-1.7.0.dev1.tar.gz
make: *** [Makefile:864: installtest] Error 1
Error: Process completed with exit code 2.

2024-04-15 14:53 UTC, andy-maier commented
The error happened because setuptools had a bug in 69.3.0 (the one used in your failing test runs) and 69.4.0 where it trimmed away parts of the package version. See https://github.com/pypa/setuptools/issues/4302.

They yanked the setuptools versions that had the issue and released a fix.
I have restarted the test runs for his PR and they should now succeed.

2024-04-15 14:58 UTC, andy-maier requested changes

2024-04-15 14:58 UTC, andy-maier commented on docs/appendix.rst
> +sent from at least the OpenPegasus server, this may be due to timout/retry
typo: "timout"

2024-04-15 14:58 UTC, andy-maier commented on docs/appendix.rst
> +the WBEM server receives a zero length response immediatly after sending the
typo: "immediatly"

2024-04-15 14:58 UTC, andy-maier commented on docs/appendix.rst
> +an error and the retry process started.  If any timeouts or time checks in the
"is started" ?

2024-04-15 15:00 UTC, andy-maier commented on docs/appendix.rst
> +sent from at least the OpenPegasus server, this may be due to timout/retry
DONE

2024-04-15 15:00 UTC, andy-maier commented on docs/appendix.rst
> +the WBEM server receives a zero length response immediatly after sending the
DONE

2024-04-15 15:00 UTC, andy-maier commented on docs/appendix.rst
> +an error and the retry process started.  If any timeouts or time checks in the
DONE

2024-04-15 15:01 UTC, andy-maier approved these changes
Fixed some typos.

2024-04-15 15:15 UTC, KSchopmeyer commented on docs/appendix.rst
> +the WBEM server receives a zero length response immediatly after sending the
done

2024-04-15 15:23 UTC, KSchopmeyer commented on docs/appendix.rst
> +an error and the retry process started.  If any timeouts or time checks in the
DONE

2024-04-15 19:33 UTC, andy-maier commented
Replaced by PR #3148

2024-04-15 19:33 UTC, closed without merging