Remove max version limit on build package.
pywbem/pywbem pull request #3203
Opened 2024-07-09 19:54 UTC by KSchopmeyer

See commit message for details.

2024-07-14 17:37 UTC, andy-maier requested changes

2024-07-14 17:37 UTC, andy-maier commented on Makefile
> +	-$(call RMDIR_FUNC,build -vv $(package_name).egg-info-INFO .eggs)
I don't think the `-vv` should stay in.

2024-07-15 14:37 UTC, KSchopmeyer commented on Makefile
> +	-$(call RMDIR_FUNC,build -vv $(package_name).egg-info-INFO .eggs)
(KS) Fixed

2024-07-15 15:47 UTC, andy-maier approved these changes

2024-07-15 15:47 UTC, merged